#!/usr/bin/env bash
# configures nginx to be running, and listening on port 80

sudo sed -E -i 's/(listen [0-9]+)/listen 80/' /etc/nginx/sites-enabled/default
sudo sed -E -i 's/(listen \[::\]:[0-9]+)/listen [::]:80/' /etc/nginx/sites-enabled/default
sudo service nginx restart
