#!/usr/bin/env bash
# A scirpt that displays To infinity and beyond indefinitely, and is immune to
# SIGTERM

trap "echo I am invincible!!!" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done

