#!/usr/bin/env bash
#configure nginx user

# Check if the nginx user already exists
if ! id "nginx" >/dev/null 2>&1; then
    sudo useradd -r nginx
fi
pkill apache2
chmod -R 644 /etc/nginx
sed -i 's/user www-data;/#user www-data;/' /etc/nginx/nginx.conf
sed -i '/#user www-data;/a user nginx;' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
